<?xml version="1.0" encoding="utf-8"?><Database Name="STORE" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-FSDGEUV\SQLEXPRESS;Initial Catalog=STORE;Integrated Security=True" SettingsObjectName="DB_Console.Properties.Settings" SettingsPropertyName="STOREConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ACCOUNT" Member="ACCOUNTs">
    <Type Name="ACCOUNT">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="balance" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="ACCOUNT_ORDER" Member="ORDERs" ThisKey="id" OtherKey="account_id" Type="ORDER" />
      <Association Name="ACCOUNT_PAYMENT" Member="PAYMENTs" ThisKey="id" OtherKey="account_id" Type="PAYMENT" />
    </Type>
  </Table>
  <Table Name="dbo.ITEM" Member="ITEMs">
    <Type Name="ITEM">
      <Column Name="price" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="ITEM_ORDER_LINE" Member="ORDER_LINEs" ThisKey="id" OtherKey="item_id" Type="ORDER_LINE" />
    </Type>
  </Table>
  <Table Name="dbo.ORDER_LINE" Member="ORDER_LINEs">
    <Type Name="ORDER_LINE">
      <Column Name="item_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="ITEM_ORDER_LINE" Member="ITEM" ThisKey="item_id" OtherKey="id" Type="ITEM" IsForeignKey="true" />
      <Association Name="ORDER_ORDER_LINE" Member="ORDER" ThisKey="order_id" OtherKey="id" Type="ORDER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ORDERS" Member="ORDERs">
    <Type Name="ORDER">
      <Column Name="total_cost" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="account_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="ORDER_ORDER_LINE" Member="ORDER_LINEs" ThisKey="id" OtherKey="order_id" Type="ORDER_LINE" />
      <Association Name="ACCOUNT_ORDER" Member="ACCOUNT" ThisKey="account_id" OtherKey="id" Type="ACCOUNT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PAYMENT" Member="PAYMENTs">
    <Type Name="PAYMENT">
      <Column Name="account_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="ACCOUNT_PAYMENT" Member="ACCOUNT" ThisKey="account_id" OtherKey="id" Type="ACCOUNT" IsForeignKey="true" />
    </Type>
  </Table>
</Database>